package com.company.persistence;

public enum ActionType {
    ADD_CLIENT,
    ADD_COMEDY,
    ADD_ANIMATION,
    ADD_THRILLER,
    ADD_ROMANTIC,
    ADD_HORROR,
    ADD_DRAMA,
    SOLD_TICKET,
    DISPLAYED_AVAILABLE_TICKETS,
    UPDATE_CLIENT_AGE,
    UPDATE_CLIENT_SUBSCRIPTION,
    DISPLAYED_ALL_MOVIES,
    DISPLAYED_MOVIES_FROM_CATEGORY,
    DISPLAYED_CLIENTS,
    DISPLAYED_SOLD_TICKETS,
    DELETED_CLIENT,
    DELETED_MOVIE
}